### ISSUE TITLE
Missing localization

### ISSUE THREAD

**Issue by svenow** [systopia/de.systopia.mailattachment#6]
Extension lacks localisation support.

All viewable text is currently in English language only, which results in mixed language forms if another language than English is selected in Drupal/CiviCrm.

- a _l10n_ folder should be added to root folder of extension
- a _de_DE/LC_MESSAGES_ sub-folder should be added to _l10n_ for localization in German language
- all text within E::ts()` (php) and `{ts}{/ts}` (smarty) wrappers should be localized to German language
  - _l10n/mailattachment.pot_ contains loclization keywords (text taken from ts-wrappers)
  - _l10n/de_DE/LC_MESSAGES/mailattachment.po_ contains localized German language text for each keyword
  - _l10n/de_DE/LC_MESSAGES/mailattachment.mo_ contains the compiled/binary representation of localized text

**Comment by jensschuppe** [comment]
#7 adds the localization template.
